version: '3.9'
services:
  app:
    image: 'openschools-dev'
    restart: always
    ports:
      - "3000:3000"
    container_name: openschools-frontend-dev
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:9000
      - PORT=3000
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==dev"
