version: '3.9'
services:
    nextjs:
        image: 'nextjs-dev'
        restart: always
        ports:
            - '3000:3000'
        environment:
            - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
            - NEXT_PUBLIC_apiKey=${NEXT_PUBLIC_apiKey}
            - NEXT_PUBLIC_authDomain=${NEXT_PUBLIC_authDomain}
            - NEXT_PUBLIC_projectId=${NEXT_PUBLIC_projectId}
            - NEXT_PUBLIC_storageBucket=${NEXT_PUBLIC_storageBucket}
            - NEXT_PUBLIC_messagingSenderId=${NEXT_PUBLIC_messagingSenderId}
            - NEXT_PUBLIC_appId=${NEXT_PUBLIC_appId}
            - NEXT_PUBLIC_measurementId=${NEXT_PUBLIC_measurementId}
            - PORT=3000
        volumes:
            - /var/www/nextjs/.next:/opt/app/.next
#            - /var/www/nextjs/public:/opt/app/public
        deploy:
            placement:
                constraints:
                    - 'node.labels.TAG==dev'
