version: '3.9'
services:
    app:
        image: 'nextjs-prod'
        restart: always
        ports:
            - '3000:3000'
        environment:
            - NEXT_PUBLIC_BASE_URL=http://localhost:9000
            - PORT=3000
        deploy:
            placement:
                constraints:
                    - 'node.labels.TAG==prod'
