name: CI build
on:
#  workflow_call:
#    secrets:
#      GOOGLE_API_KEY:
#        required: true
#      GOOGLE_MAPS_API_KEY:
#        required: true
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
      - '!dev'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      # Registry login step intentionally missing

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx
      - name: Create env file
        run: |
          touch .env
#          echo GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} >> .env
#          echo GOOGLE_MAPS_API_KEY=${{secrets.GOOGLE_MAPS_API_KEY}} >> .env
      - name: Look up existing images
        run: docker image ls
      - name: Build local image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: dev.Dockerfile
          load: true
          tags: nextjs-dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Look up images
        run: docker image ls
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: apps/
      - name: Install yarn globally
        run: npm install -g yarn
      - name: Create env file
        run: |
          touch .env
          echo GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} >> .env
          echo GOOGLE_MAPS_API_KEY=${{secrets.GOOGLE_MAPS_API_KEY}} >> .env
      - name: Install dependencies
        run: yarn install
      - name: Yarn build
        run: yarn build